// Include headers of different port elements:
#include "port_system.h"
#include "port_usart.h"
#include "stm32f4xx.h"

//------------------------------------------------------
// STATIC VARIABLES
//------------------------------------------------------

static volatile uint32_t msTicks = 0; /*!< Variable to store millisecond ticks */

//------------------------------------------------------
// PUBLIC FUNCTIONS
//------------------------------------------------------

/**
 * @brief Returns the number of milliseconds since the system started.
 *
 * @note While this function is declared in port_system.h, it is defined here because
 * msTicks is a static variable that is only visible in this file.
 * @retval number of milliseconds since the system started.
 */
uint32_t port_system_get_millis()
{
  return msTicks;
}


//------------------------------------------------------
// INTERRUPT SERVICE ROUTINES (ISR)
//------------------------------------------------------

/**
 * @brief This function handles System tick timer.
 */
void SysTick_Handler(void)
{
  msTicks += 1;
}

/**
 * @brief  Interrupt service routine for USART 1.
 *
 * @note   This ISR is called when the USART 1 generates an interrupt. The program flow jumps to this ISR and we need to check which interrupt has been generated.
 *
 * If the interrupt is generated by the RXNE flag, the received data is read from the USART 1 data register. If the interrupt is generated by the TXE flag, the data to be transmitted is written to the USART 1 data register. If the interrupt is generated by the TC flag, the TC flag is cleared.
 */
void USART1_IRQHandler(void)
{
    /* If it is enabled the reception interrupt */
    if (USART1->CR1 & USART_CR1_RXNEIE)
    {
        /* Check if the interrupt is generated by the RXNE flag */
        if (USART1->SR & USART_SR_RXNE)
        {
            port_usart1_read(); // Read the data of the data register
        }
    }

    /* If it is enabled the transmission complete interrupt */
    if (USART1->CR1 & USART_CR1_TCIE)
    {
        /* Check if the interrupt is generated by the TC flag */
        if (USART1->SR & USART_SR_TC)
        {
            USART1->SR &= ~USART_SR_TC; // Clear the TC flag
        }
    }
}
